#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
This script aims to plot the autocorrelation  in compound river flow-water leel pairs. The idea is to first, evaluate whether the
autocorrelation (correlation of atime series with itself) exist and then remove it

Author: MOhammad Bizhanimanzar
"""

import matplotlib.pyplot as plt
import pandas as pd
import os


name = 'du_Loup'
pth = '/home/mohammad/Dossier_travail/705300_rehaussement_marin/3- Data/LOT3/Extraction_Qjourn_Ouranos_LOT3.xlsx'

data_Q = pd.read_excel(pth, index_col = None)

st = {'Yamaska':'MONT00003', 'Richelieu':'MONT00502', 'Saint_Jacques':'MONT01296', 'Saint_Regis':'MONT01317', 'Chateauguay':'MONT01335', 'Maskinonge':'SLNO00496', 'Assomption':'SLNO00563', 'du_Loup':'SLNO00847', 'Saint_Maurice':'SLNO00930',
      'Batiscan':'SLNO02927', 'Becancour':'SLSO00767', 'Nicolet':'SLSO00941', 'Saint_Francois':'SLSO01193'}  

idd = st[name]
Q = pd.DataFrame({'Q(m3/s)':data_Q[idd][0:],
                   'Date':data_Q['Date'][0:].astype('datetime64[ns]')})

Q['Date'] = pd.to_datetime(Q['Date'])
Q = Q.set_index('Date')
Q = Q.loc['1968-01-01':'2019-12-31']  

# Transform the Date to year, month, and day columns
Q['year'] = pd.DatetimeIndex(Q['Date']).year
Q['month'] = pd.DatetimeIndex(Q['Date']).month
Q['day'] = pd.DatetimeIndex(Q['Date']).day









name = 'du_LOup'
pth2 = os.path.join('/home/mohammad/Dossier_travail/705300_rehaussement_marin/3- Data/LOT3/'+name+'/WLcondQ.csv')
data_Q= pd.read_csv(pth2, index_col = None)



fig,ax = plt.subplots(1,1,sharex = True,figsize=(5, 2),dpi=300)
plt.title("Autocorrelation Plot Q in WLcondQ")
 
# Providing x-axis name.
plt.xlabel("Lags")
 
# Plotting the Autocorrelation plot.
plt.acorr(Q['Q(m3/s)'], maxlags = 20)
 
# Displaying the plot.
print("The Autocorrelation plot for the data is:")
plt.grid(True)
 
plt.show()




















